### ISSUE TITLE
codegenApolloMock with fragments in separate files

### ISSUE THREAD

**Issue by Pikachews** [rubengrill/apollo-typed-documents#14]
I have my project setup something like this:

`src/.../fragment.graphql`
```
fragment TestFragment {
   ...
}
```

`src/../query.graphql`
```
query TestQuery {
   test {
      ...TestFragment
   }
}
```

`codegen.yml`
```
overwrite: true
schema: "schema.graphql"
documents: "src/**/*.graphql"
generates:
  ./mocks.ts:
    plugins:
      - "apollo-typed-documents/lib/codegenApolloMock"
```

However, when I run codegen, it does not seem to recognize TestFragment, giving me the following error:
```
Error: Fragment "TestFragment" not defined
```
unless the fragment is in the same file as the query.
